<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformeRepository extends EntityRepository
{
  public function queryObtenerInforme($rastreadorId)
  {
      $qb = $this->createQueryBuilder('inf');
      $qb ->where('inf.rastreador = :rastreadorId')
          ->setParameter('rastreadorId', $rastreadorId)
          ->orderBy('inf.id', 'DESC')
          ->setMaxResults(1);
      return $qb->getQuery()->getOneOrNullResult();
  }

}
